[2024-11-12T10:09:01.016+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T10:09:01.044+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_data.fetch_data_from_api scheduled__2024-11-12T10:06:00+00:00 [queued]>
[2024-11-12T10:09:01.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_data.fetch_data_from_api scheduled__2024-11-12T10:06:00+00:00 [queued]>
[2024-11-12T10:09:01.053+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T10:09:01.201+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data_from_api> on 2024-11-12 10:06:00+00:00
[2024-11-12T10:09:01.206+0000] {standard_task_runner.py:64} INFO - Started process 262 to run task
[2024-11-12T10:09:01.209+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_data', 'fetch_data_from_api', 'scheduled__2024-11-12T10:06:00+00:00', '--job-id', '615', '--raw', '--subdir', 'DAGS_FOLDER/***_producer.py', '--cfg-path', '/tmp/tmpk4h79t0l']
[2024-11-12T10:09:01.211+0000] {standard_task_runner.py:91} INFO - Job 615: Subtask fetch_data_from_api
[2024-11-12T10:09:01.266+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_data.fetch_data_from_api scheduled__2024-11-12T10:06:00+00:00 [running]> on host b51985a4b8f1
[2024-11-12T10:09:01.363+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bich Ly' AIRFLOW_CTX_DAG_ID='fetch_data' AIRFLOW_CTX_TASK_ID='fetch_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T10:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-12T10:06:00+00:00'
[2024-11-12T10:09:01.363+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T10:09:01.430+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=10.0.2.15:9092 <connecting> [IPv4 ('10.0.2.15', 9092)]>: connecting to 10.0.2.15:9092 [('10.0.2.15', 9092) IPv4]
[2024-11-12T10:09:01.431+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=10.0.2.15:9092 <connecting> [IPv4 ('10.0.2.15', 9092)]>: Connection complete.
[2024-11-12T10:10:06.028+0000] {airflow_producer.py:33} ERROR - An error occurred while fetching data: HTTPSConnectionPool(host='data.cityofnewyork.us', port=443): Max retries exceeded with url: /resource/h9gi-nx95.json?%24order=crash_date+DESC (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
[2024-11-12T10:10:06.036+0000] {airflow_producer.py:43} ERROR - No data fetched; exiting the stream.
[2024-11-12T10:10:06.039+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-12T10:10:06.039+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T10:10:06.061+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=10.0.2.15:9092 <connected> [IPv4 ('10.0.2.15', 9092)]>: Closing connection. 
[2024-11-12T10:10:06.085+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fetch_data, task_id=fetch_data_from_api, run_id=scheduled__2024-11-12T10:06:00+00:00, execution_date=20241112T100600, start_date=20241112T100901, end_date=20241112T101006
[2024-11-12T10:10:06.137+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-12T10:10:06.195+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-12T10:10:06.204+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
